-- 1. TABELLEN RESETTEN (Let op: Verwijdert alle data!)
drop table if exists public.messages cascade;
drop table if exists public.rooms cascade;
drop table if exists public.profiles cascade;

-- 2. TABELLEN AANMAKEN
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  email text,
  created_at timestamptz default now()
);

create table public.rooms (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  password text,
  is_private boolean default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.rooms(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  user_name text,
  content text not null,
  created_at timestamptz default now()
);

-- 3. AUTO-PROFIEL LOGICA (Reset & Creatie)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. REALTIME ACTIVEREN
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.rooms, public.messages;

-- 5. ROW LEVEL SECURITY (RLS) INSTELLEN
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.messages enable row level security;

-- Policies voor Profiles
create policy "Ingecheckte profielen zijn leesbaar" on public.profiles 
  for select using (auth.role() = 'authenticated');

-- Policies voor Rooms
create policy "Kamers zijn zichtbaar voor iedereen" on public.rooms 
  for select using (true);
create policy "Iedereen mag kamers maken" on public.rooms 
  for insert with check (auth.role() = 'authenticated');

-- Policies voor Messages
create policy "Berichten lezen als je bent ingelogd" on public.messages 
  for select using (auth.role() = 'authenticated');
create policy "Berichten sturen als je bent ingelogd" on public.messages 
  for insert with check (auth.role() = 'authenticated');
